In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
lin_spaced_arr = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr)

[  0  25  50  75 100]


In [5]:
lin_spaced_arr = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr)

[  0  25  50  75 100]


In [6]:
c = np.arange(1.25, 101.25, dtype=float)
print(c)

[  1.25   2.25   3.25   4.25   5.25   6.25   7.25   8.25   9.25  10.25
  11.25  12.25  13.25  14.25  15.25  16.25  17.25  18.25  19.25  20.25
  21.25  22.25  23.25  24.25  25.25  26.25  27.25  28.25  29.25  30.25
  31.25  32.25  33.25  34.25  35.25  36.25  37.25  38.25  39.25  40.25
  41.25  42.25  43.25  44.25  45.25  46.25  47.25  48.25  49.25  50.25
  51.25  52.25  53.25  54.25  55.25  56.25  57.25  58.25  59.25  60.25
  61.25  62.25  63.25  64.25  65.25  66.25  67.25  68.25  69.25  70.25
  71.25  72.25  73.25  74.25  75.25  76.25  77.25  78.25  79.25  80.25
  81.25  82.25  83.25  84.25  85.25  86.25  87.25  88.25  89.25  90.25
  91.25  92.25  93.25  94.25  95.25  96.25  97.25  98.25  99.25 100.25]


In [7]:
char_arr = np.array('Welcome to Math for ML!')
print(char_arr)
print(char_arr.dtype)

Welcome to Math for ML!
<U23


In [8]:
empt_arr = np.empty(3)
print(empt_arr)

[3. 2. 1.]


In [9]:
rand_arr = np.random.rand(3)
print(rand_arr)

[0.5621936  0.84436609 0.6228872 ]


In [10]:
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [11]:
# 1-D array 
one_dim_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
                one_dim_arr, # the array to be reshaped
               (3,3) # dimensions of the new array
              )
# Print the new 2-D array with two rows and three columns
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
multi_dim_arr.ndim

2

In [13]:
multi_dim_arr.shape

(3, 3)

In [14]:
multi_dim_arr.size

9

In [15]:
arr_1 = np.array([3, 9, 6])
arr_2 = np.array([1, 2, 3])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 / arr_2
print((multiplication))

[ 4 11  9]
[2 7 3]
[3.  4.5 2. ]


In [16]:
a = ([1, 2, 3, 4, 5])
print(a == a[:] == a[::])

True


In [17]:
two_dim = np.array(([1, 2, 3],
          [4, 5, 6], 
          [7, 8, 9]))

In [22]:
sliced_two_dim_cols = two_dim[1:3,1:2]
print(sliced_two_dim_cols)

[[5]
 [8]]


In [23]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])

In [24]:
# Stack the arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)


[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [25]:
# Stack the arrays vertically
vert_stack = np.hstack((a1, a2))
print(vert_stack)


[[1 1 3 3]
 [2 2 4 4]]
